include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    missing_required_param: error

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors

format:
  line-length: 150